## About Numpy 

In [5]:
##how numpy works
##numpy is multidimentional array library
##you can use numpy as to store data in 1D,2D and 3D array
##Advantages of numpy over list :-
##numpy is fast and list is very slow
##why numpy is faster 
##because numpy uses int32 representation and lists representation uses more space in python 
##faster to read less bytes of memory
##numpy uses contigeous memory cells 


In [3]:
import numpy as np

## The Basics of numpy

In [4]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [5]:
b =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Get your number dimensions
a.ndim

1

In [7]:
b.ndim

2

In [8]:
#get shape
#shape means rows and columns(rows,cols)
a.shape

(3,)

In [9]:
b.shape

(3, 3)

In [10]:
#get size
a.dtype

dtype('int32')

In [11]:
a.itemsize

4

In [12]:
#get total size 
a.nbytes

12

## Accesing changing elements, rows, columns, etc 

In [13]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [14]:
a.size

14

In [15]:
a.shape

(2, 7)

In [16]:
a[1, 5]

13

In [17]:
#Get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [18]:
a[:,1]

array([2, 9])

In [19]:
a[1,5] = 20 

In [20]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [21]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-d example

In [22]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [23]:
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
b[0,0:]

array([1, 2, 3])

In [25]:
c[:,:,1]

array([[2, 4],
       [6, 8]])

In [26]:
c[:,0,:]

array([[1, 2],
       [5, 6]])

In [27]:
#replacing
c[:,0,:] = [[3,3],[4,4]]

In [28]:
c

array([[[3, 3],
        [3, 4]],

       [[4, 4],
        [7, 8]]])

In [29]:
d = np.array([2,2,3])

In [30]:
d

array([2, 2, 3])

## Initializing different types of array

In [31]:
#all zeros

In [32]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [34]:
#any other number
np.full((2,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [35]:
np.full_like(c.shape,4)

array([4, 4, 4])

In [36]:
c.shape

(2, 2, 2)

In [37]:
#initializing array of random decimal numbers
np.random.rand(4,2)

array([[0.54232799, 0.1916347 ],
       [0.97104898, 0.27970323],
       [0.83349324, 0.45577424],
       [0.30487266, 0.72178313]])

In [38]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
#repeating the array 
ar = np.array([[1,2,3]])
r1 = np.repeat(ar,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
np.random.randint(2,8,size=(3,5))

array([[7, 3, 3, 3, 6],
       [4, 5, 2, 3, 5],
       [3, 7, 6, 2, 5]])

In [41]:
type(ar)

numpy.ndarray

In [42]:
a = np.full((5,5),1)
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [43]:
a[1,1:-1] = 0
a[2,1:-1] = 0
a[3,1:-1] = 0
a[2,2] = 9
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [44]:
a = np.ones((5,5))
print(a)
b = np.zeros((3,3))
print(b)
b[1,1] = 9
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [45]:
a[1:4,1:4] = b

In [46]:
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Mathematics


In [47]:
a = np.array([1,2,3,4])

In [48]:
a + 2

array([3, 4, 5, 6])

In [49]:
a - 2

array([-1,  0,  1,  2])

In [50]:
a-3

array([-2, -1,  0,  1])

In [51]:
a *2

array([2, 4, 6, 8])

In [52]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [53]:
#take a sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [54]:
#cosine
np.cos(a)


array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [55]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

## Linear algebra

In [56]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [57]:
#matrix multiplication
d = np.matmul(a,b)
print(d)

[[6. 6.]
 [6. 6.]]


In [58]:
#filndling the determinants
c = np.identity(3)
np.linalg.det(c)
np.linalg.det(d)

0.0

In [59]:
# Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## Statestics

In [60]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.min(stats)

1

In [62]:
np.max(stats)

6

In [63]:
np.min(stats, axis=1)

array([1, 4])

In [64]:
np.max(stats, axis=1)

array([3, 6])

In [85]:
np.min(stats, axis = 0)

array([1, 2, 3])

In [66]:
np.sum(stats)

21

## Reorganiznig array

In [67]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [68]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
 
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [69]:
#horizontally staking vectors
h1 = np.zeros((2,2))
print(h1)
h2 = np.ones((2,2))
print(h2)
np.hstack((h1,h2))

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

## Miscllaneous 

### load data from files

In [79]:
filedata = np.genfromtxt('numpy practise.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)
#columns needed to be of same number

[[          1           2           3           5           4          89
            6          54           6           3          77         889
           44         566         122 -2147483648]
 [        544          55           6           3           7          89
            7           9           8           0          10          22
           35          14          15          16]]


In [77]:
pwd


'C:\\Users\\piyus'

## Advance indexing
### boolean masking

In [80]:
filedata>50

array([[False, False, False, False, False,  True, False,  True, False,
        False,  True,  True, False,  True,  True, False],
       [ True,  True, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False]])

In [83]:
# for getting only values greater than 50
filedata[filedata>100]

array([889, 566, 122, 544])

In [84]:
#you can index with list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,3,7]]

array([2, 4, 8])

In [86]:
np.any(filedata > 50 ,axis=0) #axis = 0 - coulmn wise operations

array([ True,  True, False, False, False,  True, False,  True, False,
       False,  True,  True, False,  True,  True, False])

In [88]:
np.any(filedata > 50 ,axis=1)  #axis = 1 - row wise operations

array([ True,  True])

## puzzle